### ISSUE TITLE
Can we dismiss the dropdown menu items by clicking outside?

### ISSUE THREAD

**Issue by minhdanh** [kholifanalfon/bs_flutter_buttons#1]
Hi, thanks for the plugin.
I'm evaluating it and trying to create a dropdown menu. But when I click on the button menu, the menu items are displayed, but at this time I cannot dismiss the menu by clicking outside.
How can I do that?
Thanks!

**Comment by kholifanalfon** [comment]
Hello, I also just found this problem and I have fixed it in version 1.2.7. You can use `OverlayDropdownButton.removeAll();` on the scaffold with `onTap` gesture detector

```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: GestureDetector(
        onTap: () {
          OverlayDropdownButton.removeAll();
        },
        child: Scaffold(),
      ),
    );
  }
```

I hope this can fix your problem, thanks
